"""add images table

Revision ID: 7e1e99d2bd8b
Revises: 34f408359fd0
Create Date: 2025-04-13 11:54:30.798006

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7e1e99d2bd8b"
down_revision: Union[str, None] = "34f408359fd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "images",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_url"),
    )
    op.add_column(
        "users",
        sa.Column("avatar_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_foreign_key(None, "users", "images", ["avatar_id"], ["id"])
    op.drop_column("users", "photo_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("photo_url", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "avatar_id")
    op.drop_table("images")
    # ### end Alembic commands ###
